version: "3"
services:
  web:
    container_name: app
    build: .
    ports:
      - "9000:9000"
    command: pm2-runtime .docker/pm2/docker.json
    environment:
      - NODE_ENV=docker
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - webnet
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_DB_NAME=coderecess
      - MONGO_AUTH_USER=user
      - MONGO_AUTH_PASSWORD=pass
    volumes:
      - ./.docker/mongodb/:/docker/
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet: